services:
  - type: web
    name: healthcure
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://healthcure_db_user:4GAHXJD72MeNLxR1IgN5IouekkOXdhaV@dpg-d8e8npi8qa3s73b97l6g-a/healthcure_db